// <auto-generated />
using Grinder.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Grinder.DataAccess.Migrations
{
    [DbContext(typeof(GrinderContext))]
    partial class GrinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Grinder.DataAccess.AdminUser", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Username");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Grinder.DataAccess.ChatToMonitor", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Username");

                    b.ToTable("ChatsToMonitor");
                });

            modelBuilder.Entity("Grinder.DataAccess.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ChatId", "UserId")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Grinder.DataAccess.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username", "UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
