name: Deploy everything to Azure 

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy everything to Azure
      env:
        DOTNETRU_DEPLOY_APPID: ${{ secrets.DOTNETRU_DEPLOY_APPID }}
        DOTNETRU_DEPLOY_PWD: ${{ secrets.DOTNETRU_DEPLOY_PWD }}
        DOTNETRU_DEPLOY_TENANT: ${{ secrets.DOTNETRU_DEPLOY_TENANT }}
        VAHTER_CONFIG: ${{ secrets.VAHTER_CONFIG }}
      run: |
        cd src/Grinder.Farmer
        dotnet run --all
