name: Deploy docker image

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - "**.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push docker image to registry
      run: |
        cd src/Grinder.Farmer
        dotnet run
