name: Deploy docker image

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - "**.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push docker image to registry
      env:
        DOTNETRU_DEPLOY_APPID: ${{ secrets.DOTNETRU_DEPLOY_APPID }}
        DOTNETRU_DEPLOY_PWD: ${{ secrets.DOTNETRU_DEPLOY_PWD }}
        DOTNETRU_DEPLOY_TENANT: ${{ secrets.DOTNETRU_DEPLOY_TENANT }}
        VAHTER_CONFIG: ${{ secrets.VAHTER_CONFIG }}
      run: |
        cd src/Grinder.Farmer
        dotnet run
